@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@deepseekApiKey = sk-xxxxx

### 测试 OpenAI 接口
POST http://{{host}}/api/chat/openai
Content-Type: {{contentType}}

{
  "messages": [
    {
      "role": "user",
      "content": "你好,请问你是谁？"
    }
  ]
}

### 测试 直接访问 Deepseek
POST https://api.deepseek.com/v1/chat/completions
Content-Type: {{contentType}}
Authorization: Bearer {{deepseekApiKey}}

{
  "model": "deepseek-chat",
  "messages": [
    {
      "role": "user",
      "content": "你好,请问你是谁？"
    }
  ]
}


### 测试 Deepseek 接口
POST http://{{host}}/api/chat/deepseek
Content-Type: {{contentType}}

{
  "messages": [
    {
      "role": "user",
      "content": "你好,请问你是谁？"
    }
  ]
}

### 测试 Deepseek 接口
POST http://{{host}}/api/playground/tools
Content-Type: {{contentType}}

### 测试 AI SDK Deepseek 接口
POST http://{{host}}/api/chat/ai/deepseek
Content-Type: {{contentType}}

{
  "industry": "互联网"
}

### 测试 AI SDK OpenAI 接口
POST http://{{host}}/api/chat/ai/openai
Content-Type: {{contentType}}

{
  "content": "百度网站的地址是什么？"
}

### 测试 AI SDK OpenAI 接口
POST http://{{host}}/api/playground/ai-object
Content-Type: {{contentType}}

### 测试 AI SDK OpenAI 数据流 接口
POST http://{{host}}/api/playground/ai-stream
Content-Type: {{contentType}}

### 测试 AI SDK OpenAI 相似度接口
POST http://{{host}}/api/playground/ai-embeddingts
Content-Type: {{contentType}}

{
  "query": "什么是人工智能？"
}

### 测试 AI SDK OpenAI 
POST http://{{host}}/api/playground/ai-embeddings
Content-Type: {{contentType}}

{
  "name": "人工智能",
  "description": "人工智能是计算机科学的一个分支，旨在创建能够执行通常需要人类智能的任务的系统。",
  "founder": "张三",
  "revenue": 1000000.00
}